### ISSUE TITLE
TypeError: expected Tensor as element 0 in argument 0, but got str

### ISSUE THREAD

**Issue by otpas007** [DreamInvoker/GAIN#12]
Hi! I'm trying to train the neural network, using the default values provided in the script run_GAIN_BERT.sh (I just changed the bert_path from ../PLM/bert-base-uncased to bert-base-uncased), but the training script is giving me an error after beginning. The error stack trace is as follows: 
```
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    train(opt)
  File "train.py", line 140, in train
    ht_pair_distance=d['ht_pair_distance']
  File "/home/saptakathaa/nre/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/saptakathaa/GAIN/code/models/GAIN.py", line 306, in forward
    encoder_outputs = torch.cat([encoder_outputs, self.entity_type_emb(params['entity_type'])], dim=-1)
TypeError: expected Tensor as element 0 in argument 0, but got str
```
Can you please help me in fixing it?

P.S. : The line numbers may vary by 2-3 lines as I have included some print statements to debug it myself.

**Comment by DreamInvoker** [comment]
Maybe the `params['entity_type']` contains a string not a tensor inside it.

**Comment by otpas007** [comment]
> Maybe the `params['entity_type']` contains a string not a tensor inside it.

I have checked the type of ```params['entity_type']```. It is a tensor. Whereas the type of ```encoder_outputs``` is string.

Can you please tell me the necessary modifications I have to make to run the code?

**Comment by DreamInvoker** [comment]
It's weird, `encoder_outputs ` should be a tensor. Have you changed the code?

**Comment by DreamInvoker** [comment]
`encoder_outputs` comes from the BERT outputs, are you using transformers == 3.1.0?

**Comment by otpas007** [comment]
> `encoder_outputs` comes from the BERT outputs, are you using transformers == 3.1.0?

Yeah, it was a problem relating to the version of the ```transformers``` .. I was using a higher version which was causing the issue. Now the code is running fine.
Thanks for the help and also great work done with the paper.

**Comment by DreamInvoker** [comment]
You're welcome!

**Comment by valid999** [comment]
You can replace the torch.cat or torch.stack with this problem " TypeError: expected Tensor as element 0 in argument 0, but got float " or "expected Tensor as element 0 in argument 0, but got numpy.float32 "  or " TyprError: expected tensor as element 0 in argument 0 , but got int " to torch.tensor  and it will work .
worked for me .
