### ISSUE TITLE
Training cannot be done in GPU

### ISSUE THREAD

**Issue by otpas007** [DreamInvoker/GAIN#13]
Hi! I'm trying to train the neural network, using the default values provided in the script run_GAIN_GLOVE.sh. The code is running fine but I found that the training is being done using CPU. I tried to change the devices in the code to cuda to make it train using GPU. But it didn't work and started throwing errors "GPU device not available" although my system has GPUs.

Can you please help to execute the code using GPU?

**Comment by DreamInvoker** [comment]
We set gpu_id in the [shell script](https://github.com/DreamInvoker/GAIN/blob/178344cf00789c7ba05cfe4dca90df4b17c2caa9/code/run_GAIN_GloVe.sh#L2), please run the code following the [intructions](https://github.com/DreamInvoker/GAIN#4-training) in the README.md.
