### ISSUE TITLE
文档的最大长度设置为512，在使用自己的数据集时长度超过会报错，应该修改哪些地方？

### ISSUE THREAD

**Issue by baozi-lala** [DreamInvoker/GAIN#15]
调大document_max_length=1500仍然报错：RuntimeError: The size of tensor a (512) must match the size of tensor b (1500) at non-singleton dimension 0

**Comment by DreamInvoker** [comment]
您好，感谢对我们工作的关注！

GloVe 需改的地方：
[line1](https://github.com/DreamInvoker/GAIN/blob/178344cf00789c7ba05cfe4dca90df4b17c2caa9/code/data.py#L529)
[line2](https://github.com/DreamInvoker/GAIN/blob/178344cf00789c7ba05cfe4dca90df4b17c2caa9/code/data.py#L30)

BERT需要改的地方：
[line1](https://github.com/DreamInvoker/GAIN/blob/178344cf00789c7ba05cfe4dca90df4b17c2caa9/code/data.py#L529)
[line2](https://github.com/DreamInvoker/GAIN/blob/178344cf00789c7ba05cfe4dca90df4b17c2caa9/code/data.py#L275)
[line3](https://github.com/DreamInvoker/GAIN/blob/178344cf00789c7ba05cfe4dca90df4b17c2caa9/code/models/GAIN.py#L662)

不过BERT版本暂不支持大于512的输入。
