### ISSUE TITLE
cuda版本

### ISSUE THREAD

**Issue by baozi-lala** [DreamInvoker/GAIN#16]
您好，我在使用gpu的时候，产生的错误是OSError: libcublas.so.10: cannot open shared object file: No such file or directory。
我的cuda版本是11，请问一定需要10.2 的版本吗

**Comment by baozi-lala** [comment]
linux版本为：Linux version 3.10.0-1160.6.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )

**Comment by DreamInvoker** [comment]
亲测cuda11也可以跑的，我猜测是你的环境变量配置的是10吧？

**Comment by baozi-lala** [comment]
您是说dgl的版本吗，没有dgl-cu110==0.4.3的版本

**Comment by baozi-lala** [comment]
如果用超过0.5的版本又会报错

**Comment by DreamInvoker** [comment]
抱歉这么晚回复，您可以用一个虚拟环境换成cuda10版本试试。
