### ISSUE TITLE
运行报错dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 195 and 196 instea

### ISSUE THREAD

**Issue by baozi-lala** [DreamInvoker/GAIN#17]
错误提示：dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 195 and 196 instead.
数据集是完全按照DocRED的格式的。

**Comment by baozi-lala** [comment]
只修改了文档的最大长度

**Comment by QiankunPi** [comment]
> 错误提示：dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 195 and 196 instead. 数据集是完全按照DocRED的格式的。

请问您当时这个问题怎么解决的呀，我目前也遇到了这种问题，实在不知道该怎么去解决
