### ISSUE TITLE
请问用GPU运行报错是怎么回事？CPU可以正常运行

### ISSUE THREAD

**Issue by SavageChigga** [DreamInvoker/GAIN#30]
配置好readme中要求的环境和各项依赖后，设置gpu_id为0（本机只有id为0的这一张显卡），运行run_GAIN_BERT.sh后，log文件中显示：”RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 6.00 GiB total capacity; 4.30 GiB already allocated; 10.44 MiB free; 4.38 GiB reserved in total by PyTorch)“，无法继续运行。
用nvidia-smi检查GPU占用情况，显示只有10%左右的占用，后台并未运行其它程序，显存资源充足。我的GPU是RTX2060，6G显存。
我使用的CUDA版本是10.2，torch是gpu版本的1.6.0，其它依赖版本也均和readme中相同，而用CPU跑就可以成功运行，请问是哪里出了问题？
![202107211814](https://user-images.githubusercontent.com/87756820/126506957-b79dc31a-cf9e-43a3-80d4-369a8474ab70.png)

**Comment by YayangLi** [comment]
很明显是显存不够啊，换个大显存的机器吧
