### ISSUE TITLE
AttributeError: 'bytearray' object has no attribute 'contiguous'

### ISSUE THREAD

**Issue by edwarddiou** [DreamInvoker/GAIN#31]
Hi, there
I just tried to train in ubuntu 18.04, and i got an error like the title. 
Did anyone same too? 
my pytorch and dgl version is same as the github. and run in cuda10.2 
thx a lot.
<img width="893" alt="螢幕快照 2021-08-12 下午10 54 44" src="https://user-images.githubusercontent.com/63232802/129219629-4462b561-c303-4f36-99b1-d6b1b80adb0e.png">

**Comment by anonymous-15-8-2022forAAAI2023** [comment]
I get the same error as you. Could you tell me how to fix it? thx

**Comment by edwarddiou** [comment]
I am not sure,  because it's been a while...
The data.py will transform the dataset to an pkl format. Then it will save the pkl file in prepro_data.
Maybe while you were transforming, it got some mistake.  
You can try to delete the file in prepro_data, and rerun the code.

**Comment by JJJiangYH** [comment]
> 我不确定

it's work! good job
