### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by MingYangi** [DreamInvoker/GAIN#9]
你好，我想问一下，如果换个数据集的话，应该怎么把其他数据集换成您的这个数据集的格式呢？您是怎么处理的呢？期待回复！万分感谢！

**Comment by DreamInvoker** [comment]
我们没有将其他数据集处理成DocRED的格式。

不同数据集的数据格式不同，处理的方式也不同，DocRED数据集的格式在[这里](https://github.com/DreamInvoker/GAIN/tree/master/data)，你可以根据你想要用的数据集的格式来处理。
